# Generated by Django 5.0.11 on 2025-01-31 09:59

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags_alter_comment_active'),
    ]

    operations = [
        TrigramExtension()
    ]
